### ISSUE TITLE
Add semver releases 

### ISSUE THREAD

**Issue by tamccall** [guregu/dynamo#55] opened 2017-12-03 02:14 UTC
Add releases to project as defined here https://semver.org/ to allow for semantic versioning when using vendoring tools such as [glide](https://github.com/Masterminds/glide)

**Comment by sturfee-petrl** [comment] 2018-03-06 10:54
Duplicate of #48

**Comment by guregu** [comment] 2018-03-06 11:56
Soon, possibly this week, I'll make the current API 1.0.0.

**Comment by guregu** [comment] 2018-08-01 14:52
Finally done!

**Closed by guregu** 2018-08-01 14:52 UTC
