### ISSUE TITLE
Add describe table Functionality

### ISSUE THREAD

**Issue by tamccall** [guregu/dynamo#29] opened 2017-04-04 22:26 UTC
https://godoc.org/gopkg.in/aws/aws-sdk-go.v0/service/dynamodb#DynamoDB.DescribeTable

**Comment by guregu** [comment] 2017-04-05 18:46
What kind of API do you think would be good? I haven't added this yet because I can't think of anything better to do than just return a [dynamodb.TableDescription](https://godoc.org/gopkg.in/aws/aws-sdk-go.v0/service/dynamodb#TableDescription). I dislike how the AWS library has so many string pointers so we could clean it up a bit and return a slightly different struct I suppose.

**Comment by kingofsouth** [comment] 2017-04-05 23:31
Personally, I would just return the struct in the AWS SDK. While I agree that the official SDK is pretty cumbersome. I think making a complete duplicate of the AWS struct seems like a waste of time, but that is just my 2 cents.

**Comment by guregu** [comment] 2017-04-06 03:58
True, duplicating it would require a ton of new struct types of dubious utility. I think I'll have it return the AWS struct exactly or a thin wrapper around it that allows you to acccess the underlying AWS struct directly and maybe with a utility method or two, depending on whether we can find any uses for it.

**Closed** 2017-08-19 14:12 UTC
